spring:
  rabbitmq:
    addresses: 192.168.0.106
    port : 15672
    username: guest
    password: guest
    virtual-host: /
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.104:3306/adjusting?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#  profiles:
#    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entit

